# https://github.com/Huachao/vscode-restclient
@identity-api=http://localhost:5002
@product-api=http://localhost:5000

################################# Identity API #################################

###
# @name ApiRoot_Identity
GET {{identity-api}}
###


###
# @name Token
GET {{identity-api}}/connect/token?grant_type=password&client_id=clientId&client_secret=clientSecret&scope=all&username=admin_user&password=Admin@12345
Content-Type: application/json
accept: application/json
###


###
# @name Validate-Token
GET {{identity-api}}/validate-token
Content-Type: application/json
authorization: Bearer {{Token.response.body.access_token}}
accept: application/json
###

################################# Product API #################################

###
# @name ApiRoot_Product
GET {{product-api}}
###

###
# @name Create
Post {{product-api}}/api/v1/products
accept: application/json
Content-Type: application/json
authorization: Bearer {{Token.response.body.access_token}}

{
  "description": "test-desc",
  "name": "test-product",
  "price": 20,
  "inventoryId": 1,
  "count": 10
}
###

###
# @name Update
Put {{product-api}}/api/v1/products/09d7ef0b-b1ba-4c4c-a44b-9541fc8719bb
accept: application/json
Content-Type: application/json
authorization: Bearer {{Token.response.body.access_token}}

{
  "description": "test-desc",
  "name": "test-product",
  "price": 50,
  "inventoryId": 1,
  "count": 10
}
###

