// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	identity_service "github.com/meysamhadeli/shop-golang-microservices/internal/services/product-service/product/grpc_client/protos"
	mock "github.com/stretchr/testify/mock"
)

// IdentityServiceClient is an autogenerated mock type for the IdentityServiceClient type
type IdentityServiceClient struct {
	mock.Mock
}

// GetUserById provides a mock function with given fields: ctx, in, opts
func (_m *IdentityServiceClient) GetUserById(ctx context.Context, in *identity_service.GetUserByIdReq, opts ...grpc.CallOption) (*identity_service.GetUserByIdRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *identity_service.GetUserByIdRes
	if rf, ok := ret.Get(0).(func(context.Context, *identity_service.GetUserByIdReq, ...grpc.CallOption) *identity_service.GetUserByIdRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity_service.GetUserByIdRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *identity_service.GetUserByIdReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIdentityServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewIdentityServiceClient creates a new instance of IdentityServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIdentityServiceClient(t mockConstructorTestingTNewIdentityServiceClient) *IdentityServiceClient {
	mock := &IdentityServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
