// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeIdentityServiceServer is an autogenerated mock type for the UnsafeIdentityServiceServer type
type UnsafeIdentityServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedIdentityServiceServer provides a mock function with given fields:
func (_m *UnsafeIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeIdentityServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeIdentityServiceServer creates a new instance of UnsafeIdentityServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeIdentityServiceServer(t mockConstructorTestingTNewUnsafeIdentityServiceServer) *UnsafeIdentityServiceServer {
	mock := &UnsafeIdentityServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
